services:

  backend:
    build: .
    container_name: ecommerce_backend
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8081:8081"

    networks:
      - realtime-chat-app-backend_chat_network

networks:
  realtime-chat-app-backend_chat_network:
    external: true