spring:
  main:
    lazy-initialization: true

  application:
    name: Ecommerce

  datasource:
    url: ${DB_URL:jdbc:postgresql://dpg-d6pjehtactks73eefso0-a.singapore-postgres.render.com:5432/ecommerce_jzwe}
    username: ${DB_USER:venom}
    password: ${DB_PASS:5N2XMNvjMoUed72nxC2Kwy3qojORDz6n}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8080}